In [1]:
import os
import glob
import pandas as pd
import numpy as np

In [2]:
files = glob.glob(os.path.join(os.path.relpath('raw_data', start=os.curdir),'player*csv'))
files

['raw_data\\players13.csv',
 'raw_data\\players14.csv',
 'raw_data\\players15.csv',
 'raw_data\\players16.csv',
 'raw_data\\players17.csv',
 'raw_data\\players18.csv']

In [5]:
for f,filename in enumerate(files):
    temp = pd.DataFrame(pd.read_csv(filename, encoding = "ISO-8859-1"))
    year = filename.split('.')[-2][-2:]
    print('This is loop number {} covering year 20{}'.format(f,year))
    temp['year'] = year
    if f==0:
        df = temp
    else:
        df = pd.concat([df,temp])
print(df.shape)
df.head(10)

This is loop number 0 covering year 2013
This is loop number 1 covering year 2014
This is loop number 2 covering year 2015
This is loop number 3 covering year 2016
This is loop number 4 covering year 2017
This is loop number 5 covering year 2018
(1800, 17)

,RK,NAME,TEAM,POS,GMS,PASSING_YDS,PASSING_TD,INT,RUSHING_YDS,RUSHING_TD,RECEPTIONS,REC_YDS,REC_TD,FUM LST,PPG,FPTS,year
0,1,Peyton Manning,DEN,QB,16,5477,55,10,-31,1,0,0,0,6,25.6,409.98,13
1,2,Jamaal Charles,KC,RB,15,0,0,0,1287,12,70,693,7,2,25.2,378.00,13
2,3,Drew Brees,NO,QB,16,5162,39,12,52,3,0,0,0,2,22.4,357.68,13
3,4,Matt Forte IR,CHI,RB,16,0,0,0,1341,9,75,592,3,2,21.1,338.30,13
4,5,LeSean McCoy,PHI,RB,16,0,0,0,1607,9,52,539,2,1,20.7,330.60,13
5,6,Demaryius Thomas PUP,DEN,WR,16,0,0,0,0,0,92,1430,14,0,19.9,319.00,13
6,7,Josh Gordon,CLE,WR,14,0,0,0,88,0,87,1646,9,0,22.5,314.40,13
7,8,Antonio Brown P,PIT,WR,16,15,0,0,4,0,110,1499,8,0,19.3,308.90,13
8,9,AJ Green O,CIN,WR,16,0,0,0,0,0,98,1426,11,0,19.2,306.60,13
9,10,Brandon Marshall,CHI,WR,16,0,0,0,0,0,100,1295,12,0,19.1,305.50,13

In [20]:
df.sort_values(['FPTS','POS'],inplace=True)
summary_df = df.groupby(['NAME','POS']).agg({'year':['count'],'FPTS':['mean','std'],'RK':['mean','std']}).round(2)
print(summary_df.columns)
summary_df.reset_index().sort_values([('FPTS','mean')], ascending=False)

MultiIndex(levels=[['year', 'FPTS', 'RK'], ['count', 'mean', 'std']],
           labels=[[0, 1, 1, 2, 2], [0, 1, 2, 1, 2]])

                     NAME POS  year    FPTS              RK
                              count    mean     std    mean     std
529       Patrick Mahomes  QB     1  417.08     NaN    1.00     NaN
595        Saquon Barkley  RB     1  385.80     NaN    2.00     NaN
44        Antonio Brown P  WR     6  335.55   36.11    6.50    5.09
22           Alvin Kamara  RB     2  334.30   28.14    5.00    1.41
228            Drew Brees  QB     6  310.95   31.97   11.83    7.19
580        Russell Wilson  QB     6  308.74   33.93   13.83    9.62
134   Christian McCaffrey  RB     2  307.05  110.95   18.50   21.92
421       Knowshon Moreno  RB     1  296.60     NaN   14.00     NaN
103          Cam Newton P  QB     6  295.34   50.61   19.33   14.35
644           Todd Gurley  RB     4  290.50  100.88   33.50   35.93
185         David Johnson  RB     3  288.07  105.31   32.67   29.02
251     Ezekiel Elliott O  RB     3  285.93   71.67   22.33   25.01
645             Tom Brady  QB     6  285.00   33.36   20.83   12.29
483             Matt Ryan  QB     6  282.80   56.52   23.17   16.59
33          Andrew Luck D  QB     5  281.96   87.26   33.60   52.93
295          James Conner  RB     1  280.00     NaN   31.00     NaN
165          Dak Prescott  QB     3  277.80   14.85   20.67    5.13
495        Michael Thomas  WR     3  276.57   33.75   23.00    6.56
536         Philip Rivers  QB     6  275.35   11.89   22.33    4.84
55     Ben Roethlisberger  QB     6  274.98   41.39   24.83   14.61
6           Aaron Rodgers  QB     6  274.50  101.66   42.67   54.14
437          Le'Veon Bell  RB     5  271.52  106.65   44.60   67.84
535        Peyton Manning  QB     3  271.34  163.28   69.00  109.23
382           Julio Jones  WR     6  270.98   92.02   40.83   59.46
485      Matthew Stafford  QB     6  264.56   28.75   26.83   15.85
101        Calvin Johnson  WR     3  263.77   38.30   27.67   15.04
393           Kareem Hunt  RB     2  262.70   45.96   28.00   26.87
191       DeAndre Hopkins  WR     6  257.50   79.42   41.83   46.15
667           Tyreek Hill  WR     3  255.40   66.01   36.00   28.16
200  Demaryius Thomas PUP  WR     6  252.70   69.99   39.33   34.94
..                    ...  ..   ...     ...     ...     ...     ...
201      Demetrius Harris  TE     3   43.37    5.25  282.33    8.50
296         James Develin  RB     1   42.90     NaN  296.00     NaN
520             Nick Toon  WR     1   42.90     NaN  288.00     NaN
241           Edwin Baker  RB     1   42.80     NaN  284.00     NaN
315      Javontee Herndon  WR     1   42.80     NaN  287.00     NaN
555      Ricardo Lockette  WR     1   42.70     NaN  289.00     NaN
377           Josh Morgan  WR     1   42.70     NaN  285.00     NaN
9            Adam Shaheen  TE     1   42.70     NaN  288.00     NaN
147         Cooper Helfet  TE     1   42.50     NaN  290.00     NaN
79           Brandon Tate  WR     1   42.40     NaN  291.00     NaN
195        Deandre Carter  WR     1   42.30     NaN  297.00     NaN
155           Corey Grant  RB     1   41.90     NaN  291.00     NaN
81         Braxton Miller  WR     1   41.30     NaN  294.00     NaN
54             Ben Koyack  TE     1   41.10     NaN  280.00     NaN
358        Jordan Norwood  WR     2   41.05    2.33  286.50    2.12
546         Rashad Greene  WR     1   40.30     NaN  297.00     NaN
426         LaVon Brazill  WR     1   40.10     NaN  289.00     NaN
417           Kevin White  WR     1   38.60     NaN  286.00     NaN
154          Corey Fuller  WR     1   38.20     NaN  298.00     NaN
291        Jalin Marshall  WR     1   38.20     NaN  288.00     NaN
41        Anthony Sherman  FB     1   37.80     NaN  294.00     NaN
607        Stanley Havili  FB     1   37.50     NaN  296.00     NaN
407        Kenneth Farrow  RB     1   37.20     NaN  293.00     NaN
141             Cody Core  WR     1   37.00     NaN  294.00     NaN
624         Tanner McEvoy  WR     1   36.72     NaN  296.00     NaN
156           Cory Harkey  TE     1   36.30     NaN  297.00     NaN
323            Jeff Janis  WR     1   36.10     NaN  297.00     NaN
574          Ronnie Brown  RB     1   35.70     NaN  298.00     NaN
384      Junior Hemingway  WR     1   35.50     NaN  299.00     NaN
162          Da'Rel Scott  RB     1   34.50     NaN  300.00     NaN

[690 rows x 7 columns]